Contacts/Models/Kont.cs
namespace Contacts.Models
{
    public class Kont
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string MainName { get; set; }
        public string Otch { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Caption { get; set; }
    }
}

Contacts/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Contacts.Auth;
using Microsoft.Extensions.Logging;

namespace Contacts.Controllers
{
    //
    public class AccountController : Controller
    {

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLogin model)
        {
            if (ModelState.IsValid)
            {
                var loginResult = await _signInManager.PasswordSignInAsync(model.LoginProp,
                    model.Password,
                    false,
                    lockoutOnFailure: false);

                if (loginResult.Succeeded)
                {
                    if (Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }

                    return RedirectToAction("Index", "Home");
                }

            }

            ModelState.AddModelError("", "Пользователь не найден");
            return View(model);
        }


        [HttpGet]
        public IActionResult Register()
        {
            
            return View(new UserRegistration());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(UserRegistration model)
        {
            if (ModelState.IsValid)
            {
                var user = new User { UserName = model.LoginProp };
                var createResult = await _userManager.CreateAsync(user, model.Password);

                if (createResult.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    
                    return RedirectToAction("Index", "Home");
                }
                else//иначе
                {
                    foreach (var identityError in createResult.Errors)
                    {
                        ModelState.AddModelError("", identityError.Description);
                    }
                }
            }

            return View(model);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Roles()
        {
            ViewBag.Roles = _roleManager.Roles;
            return View();
        }
    }
}

Contacts/Controllers/HomeController.cs
using Contacts.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Contacts.Models;
using Contacts.DataContext;
using System.Linq;

namespace Contacts.Controllers
{
    public class HomeController : Controller
    {
        private readonly IContactsData contactsData;
        public HomeController(IContactsData ContactsData)
        {
            this.contactsData = ContactsData;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewBag.Contacts = contactsData.GetContacts();
            return View();
        }
        [AllowAnonymous]
        public IActionResult Info()
        {
            
            return View();
        }
        [Authorize(Roles = "user, admin")]
        public IActionResult Editor()
        {
            ViewBag.Contacts = contactsData.GetContacts();
            return View();
        }
        [HttpPost]
        public IActionResult GetData(string surname, string name, string otch, string phone, string address, string caption)
        {
            Kont temp = new Kont()
            {
                Surname = surname,
                MainName = name,
                Otch = otch,
                Phone = phone,
                Address = address,
                Caption = caption
            };

            contactsData.AddContact(temp);

            return Redirect("~/");
        }
        [Authorize(Roles = "admin")]
        public IActionResult DeleteData(string id)
        {
            id = id.Remove(0,id.IndexOf('-')+1);
            contactsData.RemoveContact(id);
            return Redirect("index");
        }
        public IActionResult updateData(string id, string surname, string name, string otch, string phone, string address, string caption)
        {
            id = id.Remove(0, id.IndexOf('-') + 1);
            contactsData.EditContact(id, surname, name, otch, phone, address, caption);

            return Redirect("~/");
        }
    }
}

Contacts/ViewComponent/LogoutViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Contacts.Component
{
    public class LogoutViewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }

}

Contacts/Views/Home/Editor.cshtml
@model Contacts.Views.Home.IndexModel
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>DADADAD</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Номер</th>
            <th>Адрес</th>
            <th>Описание</th>
        </tr>
        @{
            foreach (Contacts.Models.Kont kont in ViewBag.Contacts)
            {
                <form action="~/Home/UpdateData" method="post">
                <tr style="background-color: yellow; font-weight: bold">
                    <td>
                        <input type="text" value="@kont.Id" disabled="disabled" style="width: 20px" />
                    </td>
                    <td>
                        <input type="text" name="SurName" value="@kont.Surname" />
                    </td>
                    <td>
                        <input type="text" name="Name" value="@kont.MainName" />
                    </td>
                    <td>
                        <input type="text" name="Otch" value="@kont.Otch" />
                    </td>
                    <td>
                        <input type="text" name="Phone" value="@kont.Phone" />
                    </td>
                    <td>
                        <input type="text" name="Address" value="@kont.Surname" />
                    </td>
                    <td>
                        <input type="text" name="Caption" value="@kont.Caption" />
                    </td>
                    <td>
                        <input name="id" type="submit" value="изменить-@kont.Id" style="height:30px; background-color:navy;color: white; font-weight: bold" />
                    </td>
                </tr>
                </form>
            }
        }
    </table>
        </body>
</html>

Contacts/Views/Home/Index.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>ContList</title>
    <script src="~/js/JavaScript.js"></script>
</head>

<body>
    @{
        <table border="1">
            <tr>
                <th>Id</th>
                <th>Фамилия</th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>Номер</th>
                <th>Адрес</th>
                <th>Описание</th>
            </tr>
            @{
                foreach (Contacts.Models.Kont kont in ViewBag.Contacts)
                {
                    <form action="~/Home/DeleteData" method="post">
                    <tr>
                        <td>@kont.Id </td>
                        <td>@kont.Surname</td>
                        <td>@kont.MainName</td>
                        <td>@kont.Otch</td>
                        <td>@kont.Phone</td>
                        <td>@kont.Address</td>
                        <td>@kont.Caption</td>
                        <td>
                            <input name="id" type="submit" value="удалить-@kont.Id" />
                        </td>
                    </tr>
                    </form>
                }
            }
        </table>
        <a href="/Home/Info" class="btn">Add</a>
        <a href="/Home/Editor" class="btn">Edit</a>
    }

</body>
</html>

Contacts/Views/Home/Info.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>DADADAD</title>
</head>
<body>
            <form action="~/Home/GetData" method="post">
                <label>Фамилия</label>
                <input type="text" name="SurName" value="Varenkov" /><br />
                <label>Имя</label>
                <input type="text" name="Name" value="Ivan" /><br />
                <label>Отчество</label>
                <input type="text" name="Otch" value="Keshkovich" /><br />
                <label>Номер</label>
                <input type="text" name="Phone" value="+7(777)777-77-77" /><br />
                <label>Адрес</label>
                <input type="text" name="Address" value="Kupatov 27a" /><br />
                <label>Описание</label>
                <input type="text" name="Caption" value="K" /><br />
                <input type="submit" value="Отправить" />
            </form>
</body>
</html>

Contacts/Views/Shared/Components/LogoutView/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <div class="btn-group pull-right" style="width: 650px;">
        <a class="navbar-brand" href="~/">В начало</a>
        <a class="navbar-brand" href="/Home/Info">Добавить контакт</a>
        <a class="navbar-brand" herf="#">@User.Identity.Name в системе</a>
        <form method="post" asp-controller="Account" asp-action="Logout" id="logoutform" asp-antiforgery="true">
            @*<input type="submit" value="Выход"/>*@
            <a class="navbar-brand" href="#" onclick="document.getElementById('logoutform').submit()">Выход</a>
        </form>
    </div>
}
else
{
    <div class="btn-group pull-right">
        <a class="navbar-brand" href="/Account/Login">Вход</a>
        <a class="navbar-brand" href="/Account/Register">Регистрация </a>
    </div>
}

Contacts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    @* <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">*@
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>

<body class="container">
    <nav class="navbar navbar-light bg-light">
        <div> @await Component.InvokeAsync("LogoutView") </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <style>
        .container {
            padding-top: 10px;
        }

        .validation-summary-errors {
            color: #f00;
        }
    </style>
</body>
</html>